FROM continuumio/anaconda3

RUN mkdir /app

WORKDIR /app

RUN echo "conda activate demo >> ~/.bashrc"

# Make RUN commands use `bash --login`:

SHELL ["/bin/bash", "--login", "-c"]

COPY ./app /app

RUN conda env create -f demo.yaml

RUN conda init bash

ENTRYPOINT ["conda","run","-n","demo","uwsgi", "/app/demo.ini"]


