---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd-demo
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
spec:
  selector:
    app: cicd-demo
  ports:
  - protocol: TCP
    port: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
spec:
  selector:
    matchLabels:
      app: cicd-demo
  replicas: 4
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
      - name: cicd-demo
        image: docker-registry.asf.alaska.edu:5000/cicd-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
